import { createContext, useContext, useState } from "react";

const translations = {
  ar: {
    dir: "rtl",
    lang: "ar",
    nav: {
      home: "الرئيسية",
      training: "تمارين",
      tracking: "التقدم",
      profile: "الملف الشخصي",
      notifications: "الإشعارات",
    },
    notifications: {
      new: "📢 عندك إشعار جديد",
      updated: "✅ تم تحديث الجلسة",
      report: "⚡ فيه تقرير جاهز",
    },
    home: {
      title: "كيف تشعر اليوم؟",
      subtitle: "منصة ذكاء اصطناعي لمتابعة حالتك وتحسين جلسات العلاج",
      cameraBtn: "للمتابعة بالكاميرا",
      improvement: "تحسن ملحوظ",
      sessions: "جلسة علاج",
      satisfaction: "رضا العملاء",
      features: {
        reports: "تقارير مفصلة",
        monitoring: "متابعة مستمرة",
        results: "نتائج مضمونة",
        support: "دعم متخصص",
      },
      description: "يساعدك على متابعة جلسات العلاج وتقييم حالتك بسهولة",
    },
    footer: {
      brand: "Cranio AI",
      description: "منصة لمتابعة وتحليل جلسات العلاج بسهولة",
      subscribedBtn: "تم الاشتراك",
      subscribeBtn: "اشترك",
      subscribedMsg: "تم الاشتراك بنجاح",
      quickLinks: "روابط سريعة",
      links: [],
      contactUs: "تواصل معنا",
      contact: [],
      copyright: "© 2026 Cranio AI",
      privacy: "الخصوصية",
      terms: "الشروط",
      cookies: "الكوكيز",
    },
    tracking: {
      title: "التقدم",
      subtitle: "تابع تحسنك عبر الجلسات العلاجية",
      currentImprovement: "التحسن الحالي",
      daysRemaining: "أيام التمارين المتبقية",
      completedSessions: "جلسات مكتملة",
      curve: "منحنى التحسن",
      details: "تفاصيل الجلسات",
      noSessions: "لا توجد جلسات مكتملة حتى الآن",
      avgInfo:
        "بمعدل تحسن {avg}% لكل جلسة، من المتوقع الوصول لـ 100% خلال {days} يوم",
      cameraResults: "نتايج تحليل الكاميرا",
      framesAnalyzed: "إطار تم تحليله",
      avgConfidence: "متوسط الثقة",
      lastDiagnosis: "آخر تشخيص",
      clearResults: "🗑 مسح نتايج الكاميرا",
    },
    camera: {
      title: "تحليل الصورة",
      subtitle: "ارفع صورة أو التقط صورة من الكاميرا لتحليل الحالة",
      chooseMethod: "اختر طريقة إضافة الصورة",
      uploadBtn: "📁 رفع صورة من الجهاز",
      captureBtn: "📷 التقاط صورة من الكاميرا",
      uploadShort: "📁 رفع صورة",
      snapshotBtn: "📸 التقاط",
      cancelBtn: "إلغاء",
      analyzeBtn: "🔍 تحليل الصورة",
      changePhoto: "تغيير الصورة",
      viewProgress: "عرض التقدم →",
      newPhoto: "صورة جديدة",
      analyzingBtn: "جارٍ التحليل...",
      readyToCapture: "اضغط \"التقاط\" عندما تكون جاهزاً",
      statusChoose: "اختر صورة للبدء",
      statusCamera: "الكاميرا مفتوحة — التقط الصورة",
      statusReady: "الصورة جاهزة — اضغط تحليل",
      statusAnalyzing: "جارٍ تحليل الصورة...",
      statusDone: "اكتمل التحليل ✓",
      statusError: "فشل التحليل",
      cameraError: "تعذّر الوصول إلى الكاميرا. تأكد من منح الإذن.",
      invalidResponse: "الخادم لم يُرجع نتيجة صالحة.",
      networkError: "شبكة:",
      analysisFailed: "فشل التحليل",
      resultTitle: "نتيجة التحليل",
      waitingResult: "في انتظار التحليل...",
      confidence: "ثقة",
      tipsTitle: "💡 نصائح للصورة",
      tips: [
        "تأكد من إضاءة جيدة على وجهك",
        "الوجه واضح ومواجه للكاميرا مباشرة",
        "لا يوجد حواجب أو نظارات تحجب الوجه",
        "صورة واضحة وغير ضبابية",
      ],
      regions: {
        eye: "العين",
        eyebrow: "الحاجب",
        mouth: "الفم",
      },
      labels: {
        Mild: "خفيف",
        Moderate: "متوسط",
        "Moderate Severe": "شديد نسبياً",
        Moderate_Severe: "شديد نسبياً",
        Severe: "شديد",
        Normal: "طبيعي",
      },
    },
    training: {
      title: "تماريني",
      subtitle: "إليك تمارينك اليومية للحصول على أفضل النتائج",
      todayExercises: "تمارين اليوم",
      loading: "جاري التحميل...",
      noExercises: "لا يوجد تمارين اليوم",
      startBtn: "ابدأ التمارين 🚀",
      startAlert: "ابدأ التمارين! 🚀",
      statsTitle: "تمارين مكتملة اليوم",
      badge: "🎯 أحرز تقدماً!",
      completedExercises: "تمارين مكتملة",
      improvement: "التحسن",
      progress: "التقدم",
      sessionsCount: "عدد السيشنز",
      weeklyGoal: "هدف الأسبوع",
      days: "أيام",
      weeklyOverview: "نظرة عامة على الأسبوع",
      minuteUnit: "دقيقة",
      setsReps: "{sets} مجموعات - {reps} تكرار",
    },
    session: {
      logo: "Cranio AI",
      subtitle: "جلستك العلاجية اليومية",
      todaySession: "جلسة اليوم",
      duration: "المدة: 20 دقيقة",
      start: "ابدأ الجلسة 🚀",
      loading: "جارٍ التحميل...",
      loadingVideos: "جارٍ تحميل الفيديوهات...",
      noVideos: "لا توجد فيديوهات متاحة",
    },
  },

  en: {
    dir: "ltr",
    lang: "en",
    nav: {
      home: "Home",
      training: "Exercises",
      tracking: "Progress",
      profile: "Profile",
      notifications: "Notifications",
    },
    notifications: {
      new: "📢 You have a new notification",
      updated: "✅ Session updated",
      report: "⚡ A report is ready",
    },
    home: {
      title: "How are you feeling today?",
      subtitle:
        "AI platform to track your condition and improve therapy sessions",
      cameraBtn: "Track with Camera",
      improvement: "Notable Improvement",
      sessions: "Treatment Sessions",
      satisfaction: "Client Satisfaction",
      features: {
        reports: "Detailed Reports",
        monitoring: "Continuous Monitoring",
        results: "Guaranteed Results",
        support: "Expert Support",
      },
      description:
        "Helps you track your therapy sessions and assess your condition easily",
    },
    footer: {
      brand: "Cranio AI",
      description:
        "A platform for tracking and analyzing therapy sessions easily",
      subscribedBtn: "Subscribed",
      subscribeBtn: "Subscribe",
      subscribedMsg: "Successfully subscribed",
      quickLinks: "Quick Links",
      links: [],
      contactUs: "Contact Us",
      contact: [],
      copyright: "© 2026 Cranio AI",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
    },
    tracking: {
      title: "Progress",
      subtitle: "Track your improvement across therapy sessions",
      currentImprovement: "Current Improvement",
      daysRemaining: "Days Remaining",
      completedSessions: "Completed Sessions",
      curve: "Improvement Curve",
      details: "Session Details",
      noSessions: "No completed sessions yet",
      avgInfo:
        "At an average improvement of {avg}% per session, you're expected to reach 100% in {days} days",
      cameraResults: "Camera Analysis Results",
      framesAnalyzed: "Frames Analyzed",
      avgConfidence: "Avg. Confidence",
      lastDiagnosis: "Last Diagnosis",
      clearResults: "🗑 Clear Camera Results",
    },
    camera: {
      title: "Image Analysis",
      subtitle: "Upload or capture a photo to analyze your condition",
      chooseMethod: "Choose how to add your photo",
      uploadBtn: "📁 Upload from Device",
      captureBtn: "📷 Take a Photo",
      uploadShort: "📁 Upload Photo",
      snapshotBtn: "📸 Capture",
      cancelBtn: "Cancel",
      analyzeBtn: "🔍 Analyze Image",
      changePhoto: "Change Photo",
      viewProgress: "View Progress →",
      newPhoto: "New Photo",
      analyzingBtn: "Analyzing...",
      readyToCapture: "Press \"Capture\" when ready",
      statusChoose: "Choose a photo to get started",
      statusCamera: "Camera open — capture your photo",
      statusReady: "Photo ready — press Analyze",
      statusAnalyzing: "Analyzing image...",
      statusDone: "Analysis complete ✓",
      statusError: "Analysis failed",
      cameraError: "Could not access camera. Please grant permission.",
      invalidResponse: "Server returned an invalid result.",
      networkError: "Network error:",
      analysisFailed: "Analysis failed",
      resultTitle: "Analysis Result",
      waitingResult: "Waiting for analysis...",
      confidence: "Confidence",
      tipsTitle: "💡 Photo Tips",
      tips: [
        "Make sure your face is well-lit",
        "Face the camera directly",
        "No eyebrows or glasses blocking the face",
        "Clear and sharp image",
      ],
      regions: {
        eye: "Eye",
        eyebrow: "Eyebrow",
        mouth: "Mouth",
      },
      labels: {
        Mild: "Mild",
        Moderate: "Moderate",
        "Moderate Severe": "Moderately Severe",
        Moderate_Severe: "Moderately Severe",
        Severe: "Severe",
        Normal: "Normal",
      },
    },
    training: {
      title: "My Exercises",
      subtitle: "Here are your daily exercises for the best results",
      todayExercises: "Today's Exercises",
      loading: "Loading...",
      noExercises: "No exercises today",
      startBtn: "Start Exercises 🚀",
      startAlert: "Start Exercises! 🚀",
      statsTitle: "Completed Exercises Today",
      badge: "🎯 Keep it up!",
      completedExercises: "Completed",
      improvement: "Improvement",
      progress: "Progress",
      sessionsCount: "Sessions",
      weeklyGoal: "Weekly Goal",
      days: "days",
      weeklyOverview: "Weekly Overview",
      minuteUnit: "min",
      setsReps: "{sets} sets - {reps} reps",
    },
    session: {
      logo: "Cranio AI",
      subtitle: "Your daily therapy session",
      todaySession: "Today's Session",
      duration: "Duration: 20 minutes",
      start: "Start Session 🚀",
      loading: "Loading...",
      loadingVideos: "Loading videos...",
      noVideos: "No videos available",
    },
  },
};

export const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState("ar");
  const t = translations[lang];
  const toggle = () => setLang((l) => (l === "ar" ? "en" : "ar"));
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      <div dir={t.dir} lang={t.lang}>
        {children}
      </div>
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);

export default translations;