import { createContext, useContext, useState } from "react";

const translations = {
  ar: {
    dir: "rtl",
    lang: "ar",
    nav: {
      home: "الرئيسية",
      training: "تمارين",
      tracking: "التقدم",
      profile: "الملف الشخصي",
      notifications: "الإشعارات",
    },
    notifications: {
      new: "📢 عندك إشعار جديد",
      updated: "✅ تم تحديث الجلسة",
      report: "⚡ فيه تقرير جاهز",
    },
    home: {
      title: "كيف تشعر اليوم؟",
      subtitle: "منصة ذكاء اصطناعي لمتابعة حالتك وتحسين جلسات العلاج",
      cameraBtn: "للمتابعة بالكاميرا",
      improvement: "تحسن ملحوظ",
      sessions: "جلسة علاج",
      satisfaction: "رضا العملاء",
      features: {
        reports: "تقارير مفصلة",
        monitoring: "متابعة مستمرة",
        results: "نتائج مضمونة",
        support: "دعم متخصص",
      },
      description: "يساعدك على متابعة جلسات العلاج وتقييم حالتك بسهولة",
    },
    footer: {
      brand: "Cranio AI",
      description: "منصة لمتابعة وتحليل جلسات العلاج بسهولة",
      subscribedBtn: "تم الاشتراك",
      subscribeBtn: "اشترك",
      subscribedMsg: "تم الاشتراك بنجاح",
      quickLinks: "روابط سريعة",
      links: [],
      contactUs: "تواصل معنا",
      contact: [],
      copyright: "© 2026 Cranio AI",
      privacy: "الخصوصية",
      terms: "الشروط",
      cookies: "الكوكيز",
    },
    tracking: {
      title: "التقدم",
      subtitle: "تابع تحسنك عبر الجلسات العلاجية",
      currentImprovement: "التحسن الحالي",
      daysRemaining: "أيام التمارين المتبقية",
      completedSessions: "جلسات مكتملة",
      curve: "منحنى التحسن",
      details: "تفاصيل الجلسات",
      noSessions: "لا توجد جلسات مكتملة حتى الآن",
      avgInfo:
        "بمعدل تحسن {avg}% لكل جلسة، من المتوقع الوصول لـ 100% خلال {days} يوم",
      cameraResults: "نتايج تحليل الكاميرا",
      framesAnalyzed: "إطار تم تحليله",
      avgConfidence: "متوسط الثقة",
      lastDiagnosis: "آخر تشخيص",
      clearResults: "🗑 مسح نتايج الكاميرا",
    },
    camera: {
      title: "تحليل الصورة",
      subtitle: "ارفع صورة أو التقط صورة من الكاميرا لتحليل الحالة",
      chooseMethod: "اختر طريقة إضافة الصورة",
      uploadBtn: "📁 رفع صورة من الجهاز",
      captureBtn: "📷 التقاط صورة من الكاميرا",
      uploadShort: "📁 رفع صورة",
      snapshotBtn: "📸 التقاط",
      cancelBtn: "إلغاء",
      analyzeBtn: "🔍 تحليل الصورة",
      changePhoto: "تغيير الصورة",
      viewProgress: "عرض التقدم →",
      newPhoto: "صورة جديدة",
      analyzingBtn: "جارٍ التحليل...",
      readyToCapture: "اضغط \"التقاط\" عندما تكون جاهزاً",
      statusChoose: "اختر صورة للبدء",
      statusCamera: "الكاميرا مفتوحة — التقط الصورة",
      statusReady: "الصورة جاهزة — اضغط تحليل",
      statusAnalyzing: "جارٍ تحليل الصورة...",
      statusDone: "اكتمل التحليل ✓",
      statusError: "فشل التحليل",
      cameraError: "تعذّر الوصول إلى الكاميرا. تأكد من منح الإذن.",
      invalidResponse: "الخادم لم يُرجع نتيجة صالحة.",
      networkError: "شبكة:",
      analysisFailed: "فشل التحليل",
      resultTitle: "نتيجة التحليل",
      waitingResult: "في انتظار التحليل...",
      confidence: "ثقة",
      tipsTitle: "💡 نصائح للصورة",
      tips: [
        "تأكد من إضاءة جيدة على وجهك",
        "الوجه واضح ومواجه للكاميرا مباشرة",
        "لا يوجد حواجب أو نظارات تحجب الوجه",
        "صورة واضحة وغير ضبابية",
      ],
      regions: {
        eye: "العين",
        eyebrow: "الحاجب",
        mouth: "الفم",
      },
      labels: {
        Mild: "خفيف",
        Moderate: "متوسط",
        "Moderate Severe": "شديد نسبياً",
        Moderate_Severe: "شديد نسبياً",
        Severe: "شديد",
        Normal: "طبيعي",
      },
    },
    training: {
      title: "تماريني",
      subtitle: "إليك تمارينك اليومية للحصول على أفضل النتائج",
      todayExercises: "تمارين اليوم",
      loading: "جاري التحميل...",
      noExercises: "لا يوجد تمارين اليوم",
      startBtn: "ابدأ التمارين 🚀",
      startAlert: "ابدأ التمارين! 🚀",
      statsTitle: "تمارين مكتملة اليوم",
      badge: "🎯 أحرز تقدماً!",
      completedExercises: "تمارين مكتملة",
      improvement: "التحسن",
      progress: "التقدم",
      sessionsCount: "عدد السيشنز",
      weeklyGoal: "هدف الأسبوع",
      days: "أيام",
      weeklyOverview: "نظرة عامة على الأسبوع",
      minuteUnit: "دقيقة",
      setsReps: "{sets} مجموعات - {reps} تكرار",
    },
    session: {
      logo: "Cranio AI",
      subtitle: "جلستك العلاجية اليومية",
      todaySession: "جلسة اليوم",
      duration: "المدة: 20 دقيقة",
      start: "ابدأ الجلسة 🚀",
      loading: "جارٍ التحميل...",
      loadingVideos: "جارٍ تحميل الفيديوهات...",
      noVideos: "لا توجد فيديوهات متاحة",
    },
    signin: {
      description: "سجل دخولك لمتابعة جلساتك",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      forgot: "نسيت كلمة المرور؟",
      submit: "تسجيل الدخول",
      loading: "جارٍ التحميل...",
      noAccount: "ليس لديك حساب؟",
      createAccount: "أنشئ حساب",
      googleFail: "فشل تسجيل الدخول بجوجل",
      loginFail: "فشل تسجيل الدخول",
      networkError: "مشكلة في الشبكة: ",
    },
    signup: {
      description: "أنشئ حساب جديد للبدء",
      fullName: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      confirmPassword: "تأكيد كلمة المرور",
      submit: "إنشاء حساب",
      loading: "جارٍ التحميل...",
      hasAccount: "لديك حساب بالفعل؟",
      signin: "سجل دخول",
      passwordMismatch: "كلمة المرور وتأكيدها غير متطابقين",
      success: "تم إنشاء الحساب بنجاح! سجل دخولك الآن 🎉",
      googleFail: "فشل تسجيل الدخول بجوجل",
      networkError: "مشكلة في الشبكة: ",
      createFail: "فشل إنشاء الحساب",
    },
    profile: {
      loading: "جاري التحميل...",
      personalData: "البيانات الشخصية",
      fullName: "الاسم الكامل",
      fullNamePlaceholder: "أدخل اسمك الكامل",
      emailLabel: "البريد الإلكتروني",
      emailCantChange: "لا يمكن تغيير البريد الإلكتروني",
      passwordLabel: "كلمة المرور",
      passwordChangeSoon: "تغيير كلمة المرور — قريباً",
      nameRequired: "الاسم لا يمكن أن يكون فارغاً",
      saveSuccess: "تم حفظ البيانات بنجاح ✓",
      saveFail: "فشل الحفظ: ",
      saving: "جاري الحفظ...",
      saveChanges: "حفظ التغييرات",
      faq: "الأسئلة الشائعة",
      faqNoAnswer: "💬 لم تجد إجابة لسؤالك؟",
      faqContactUs: "تواصل معنا من خلال صفحة \"اتصل بنا\"",
      contactUs: "اتصل بنا",
      contactHeroTitle: "نحن هنا لمساعدتك",
      contactHeroDesc: "لا تتردد في التواصل معنا في أي وقت، فريق الدعم لدينا متاح على مدار الساعة",
      contactEmail: "البريد الإلكتروني",
      contactWhatsapp: "واتساب",
      contactWebsite: "الموقع الإلكتروني",
      followUs: "تابعنا على وسائل التواصل",
      workingHours: "🕐 ساعات العمل: يومياً من",
      workingHoursTime: "9 صباحاً - 9 مساءً",
      aboutApp: "عن التطبيق",
      version: "الإصدار 1.0.0",
      aboutDesc: "Cranio AI هو تطبيق ذكي يُقدم لك تقييمًا مبدئيًا لحالتك الصحية من خلال تحليل الوجه باستخدام تقنيات الذكاء الاصطناعي المتقدمة. نسعى لجعل الرعاية الصحية أكثر سهولة وإتاحةً للجميع.",
      appFeatures: "مميزات التطبيق",
      feature1Title: "فحص دقيق",
      feature1Desc: "تحليل متقدم بتقنيات الذكاء الاصطناعي",
      feature2Title: "خصوصية تامة",
      feature2Desc: "بياناتك مشفرة ومحمية بالكامل",
      feature3Title: "نتائج فورية",
      feature3Desc: "احصل على تقييمك في ثوانٍ معدودة",
      feature4Title: "متابعة مستمرة",
      feature4Desc: "تتبع تقدمك وتحسنك عبر الزمن",
      disclaimer: "⚠️ تنبيه: هذا التطبيق أداة فحص مبدئية فقط ولا يُغني عن استشارة الطبيب المختص للحصول على تشخيص طبي دقيق.",
      copyright: "© 2025 Cranio AI — جميع الحقوق محفوظة",
      defaultUser: "المستخدم",
      changePhoto: "اضغط لتغيير الصورة",
      ratingLabel: "تقييمك",
      completedSessions: "جلسات مكتملة",
      improvementRate: "معدل التحسن",
      completedExercises: "تمرينة مكتملة",
      accountSettings: "إعدادات الحساب",
      notifications: "الاشعارات",
      privacy: "الخصوصية",
      supportHelp: "الدعم والمساعدة",
      logout: "تسجيل الخروج",
      invalidImage: "يرجى اختيار صورة صالحة",
      imageTooLarge: "حجم الصورة يجب أن يكون أقل من 5MB",
      faqQ1: "كيف أبدأ استخدام التطبيق؟",
      faqA1: "بعد تسجيل الدخول، سيتم توجيهك تلقائيًا إلى الشاشة الرئيسية. اضغط على \"Rate via Camera\" أو \"Rate via Chat\"، ثم اتبع التعليمات الظاهرة على الشاشة.",
      faqQ2: "ما هي شروط إجراء فحص صحيح؟",
      faqA2: "يجب أن تكون في مكان جيد الإضاءة، وأن تضع الهاتف بمستوى العين، مع إزالة أي عوائق على الوجه مثل النظارات الشمسية أو الكمامات لضمان دقة التحليل.",
      faqQ3: "هل النتائج تُعتبر تشخيصًا طبيًا نهائيًا؟",
      faqA3: "لا، التطبيق هو أداة فحص مبدئي للمساعدة والتنبيه فقط. يجب دائمًا استشارة طبيب مختص للحصول على تشخيص طبي دقيق.",
      faqQ4: "كيف يتم حماية بياناتي؟",
      faqA4: "نحن نأخذ الخصوصية بجدية؛ فجميع البيانات والتحليلات مشفرة، كما أن صورك الشخصية لا تتم مشاركتها أبدًا مع أي جهات خارجية.",
    },
  },

  en: {
    dir: "ltr",
    lang: "en",
    nav: {
      home: "Home",
      training: "Exercises",
      tracking: "Progress",
      profile: "Profile",
      notifications: "Notifications",
    },
    notifications: {
      new: "📢 You have a new notification",
      updated: "✅ Session updated",
      report: "⚡ A report is ready",
    },
    home: {
      title: "How are you feeling today?",
      subtitle:
        "AI platform to track your condition and improve therapy sessions",
      cameraBtn: "Track with Camera",
      improvement: "Notable Improvement",
      sessions: "Treatment Sessions",
      satisfaction: "Client Satisfaction",
      features: {
        reports: "Detailed Reports",
        monitoring: "Continuous Monitoring",
        results: "Guaranteed Results",
        support: "Expert Support",
      },
      description:
        "Helps you track your therapy sessions and assess your condition easily",
    },
    footer: {
      brand: "Cranio AI",
      description:
        "A platform for tracking and analyzing therapy sessions easily",
      subscribedBtn: "Subscribed",
      subscribeBtn: "Subscribe",
      subscribedMsg: "Successfully subscribed",
      quickLinks: "Quick Links",
      links: [],
      contactUs: "Contact Us",
      contact: [],
      copyright: "© 2026 Cranio AI",
      privacy: "Privacy",
      terms: "Terms",
      cookies: "Cookies",
    },
    tracking: {
      title: "Progress",
      subtitle: "Track your improvement across therapy sessions",
      currentImprovement: "Current Improvement",
      daysRemaining: "Days Remaining",
      completedSessions: "Completed Sessions",
      curve: "Improvement Curve",
      details: "Session Details",
      noSessions: "No completed sessions yet",
      avgInfo:
        "At an average improvement of {avg}% per session, you're expected to reach 100% in {days} days",
      cameraResults: "Camera Analysis Results",
      framesAnalyzed: "Frames Analyzed",
      avgConfidence: "Avg. Confidence",
      lastDiagnosis: "Last Diagnosis",
      clearResults: "🗑 Clear Camera Results",
    },
    camera: {
      title: "Image Analysis",
      subtitle: "Upload or capture a photo to analyze your condition",
      chooseMethod: "Choose how to add your photo",
      uploadBtn: "📁 Upload from Device",
      captureBtn: "📷 Take a Photo",
      uploadShort: "📁 Upload Photo",
      snapshotBtn: "📸 Capture",
      cancelBtn: "Cancel",
      analyzeBtn: "🔍 Analyze Image",
      changePhoto: "Change Photo",
      viewProgress: "View Progress →",
      newPhoto: "New Photo",
      analyzingBtn: "Analyzing...",
      readyToCapture: "Press \"Capture\" when ready",
      statusChoose: "Choose a photo to get started",
      statusCamera: "Camera open — capture your photo",
      statusReady: "Photo ready — press Analyze",
      statusAnalyzing: "Analyzing image...",
      statusDone: "Analysis complete ✓",
      statusError: "Analysis failed",
      cameraError: "Could not access camera. Please grant permission.",
      invalidResponse: "Server returned an invalid result.",
      networkError: "Network error:",
      analysisFailed: "Analysis failed",
      resultTitle: "Analysis Result",
      waitingResult: "Waiting for analysis...",
      confidence: "Confidence",
      tipsTitle: "💡 Photo Tips",
      tips: [
        "Make sure your face is well-lit",
        "Face the camera directly",
        "No eyebrows or glasses blocking the face",
        "Clear and sharp image",
      ],
      regions: {
        eye: "Eye",
        eyebrow: "Eyebrow",
        mouth: "Mouth",
      },
      labels: {
        Mild: "Mild",
        Moderate: "Moderate",
        "Moderate Severe": "Moderately Severe",
        Moderate_Severe: "Moderately Severe",
        Severe: "Severe",
        Normal: "Normal",
      },
    },
    training: {
      title: "My Exercises",
      subtitle: "Here are your daily exercises for the best results",
      todayExercises: "Today's Exercises",
      loading: "Loading...",
      noExercises: "No exercises today",
      startBtn: "Start Exercises 🚀",
      startAlert: "Start Exercises! 🚀",
      statsTitle: "Completed Exercises Today",
      badge: "🎯 Keep it up!",
      completedExercises: "Completed",
      improvement: "Improvement",
      progress: "Progress",
      sessionsCount: "Sessions",
      weeklyGoal: "Weekly Goal",
      days: "days",
      weeklyOverview: "Weekly Overview",
      minuteUnit: "min",
      setsReps: "{sets} sets - {reps} reps",
    },
    session: {
      logo: "Cranio AI",
      subtitle: "Your daily therapy session",
      todaySession: "Today's Session",
      duration: "Duration: 20 minutes",
      start: "Start Session 🚀",
      loading: "Loading...",
      loadingVideos: "Loading videos...",
      noVideos: "No videos available",
    },
    signin: {
      description: "Sign in to continue your sessions",
      email: "Email",
      password: "Password",
      forgot: "Forgot password?",
      submit: "Sign In",
      loading: "Loading...",
      noAccount: "Don't have an account?",
      createAccount: "Create Account",
      googleFail: "Google sign-in failed",
      loginFail: "Login failed",
      networkError: "Network error: ",
    },
    signup: {
      description: "Create a new account to get started",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      confirmPassword: "Confirm Password",
      submit: "Create Account",
      loading: "Loading...",
      hasAccount: "Already have an account?",
      signin: "Sign In",
      passwordMismatch: "Passwords do not match",
      success: "Account created successfully! Sign in now 🎉",
      googleFail: "Google sign-in failed",
      networkError: "Network error: ",
      createFail: "Failed to create account",
    },
    profile: {
      loading: "Loading...",
      personalData: "Personal Data",
      fullName: "Full Name",
      fullNamePlaceholder: "Enter your full name",
      emailLabel: "Email",
      emailCantChange: "Email cannot be changed",
      passwordLabel: "Password",
      passwordChangeSoon: "Change password — Coming soon",
      nameRequired: "Name cannot be empty",
      saveSuccess: "Data saved successfully ✓",
      saveFail: "Save failed: ",
      saving: "Saving...",
      saveChanges: "Save Changes",
      faq: "FAQ",
      faqNoAnswer: "💬 Didn't find your answer?",
      faqContactUs: "Contact us through the \"Contact Us\" page",
      contactUs: "Contact Us",
      contactHeroTitle: "We're here to help",
      contactHeroDesc: "Don't hesitate to reach out anytime, our support team is available 24/7",
      contactEmail: "Email",
      contactWhatsapp: "WhatsApp",
      contactWebsite: "Website",
      followUs: "Follow us on social media",
      workingHours: "🕐 Working hours: Daily from",
      workingHoursTime: "9 AM - 9 PM",
      aboutApp: "About the App",
      version: "Version 1.0.0",
      aboutDesc: "Cranio AI is a smart app that provides you with a preliminary health assessment through facial analysis using advanced AI technologies. We strive to make healthcare more accessible for everyone.",
      appFeatures: "App Features",
      feature1Title: "Accurate Scan",
      feature1Desc: "Advanced analysis with AI technologies",
      feature2Title: "Full Privacy",
      feature2Desc: "Your data is encrypted and fully protected",
      feature3Title: "Instant Results",
      feature3Desc: "Get your assessment in seconds",
      feature4Title: "Continuous Tracking",
      feature4Desc: "Track your progress and improvement over time",
      disclaimer: "⚠️ Notice: This app is a preliminary screening tool only and does not replace consulting a specialist for an accurate medical diagnosis.",
      copyright: "© 2025 Cranio AI — All rights reserved",
      defaultUser: "User",
      changePhoto: "Tap to change photo",
      ratingLabel: "Your Rating",
      completedSessions: "Completed Sessions",
      improvementRate: "Improvement Rate",
      completedExercises: "Completed Exercises",
      accountSettings: "Account Settings",
      notifications: "Notifications",
      privacy: "Privacy",
      supportHelp: "Support & Help",
      logout: "Sign Out",
      invalidImage: "Please select a valid image",
      imageTooLarge: "Image size must be less than 5MB",
      faqQ1: "How do I start using the app?",
      faqA1: "After signing in, you'll be automatically directed to the home screen. Tap \"Rate via Camera\" or \"Rate via Chat\", then follow the on-screen instructions.",
      faqQ2: "What are the conditions for a proper scan?",
      faqA2: "You should be in a well-lit area, hold your phone at eye level, and remove any obstructions from your face like sunglasses or masks to ensure analysis accuracy.",
      faqQ3: "Are the results a final medical diagnosis?",
      faqA3: "No, the app is a preliminary screening tool for assistance and awareness only. Always consult a specialist for an accurate medical diagnosis.",
      faqQ4: "How is my data protected?",
      faqA4: "We take privacy seriously; all data and analyses are encrypted, and your personal photos are never shared with any third parties.",
    },
  },
};

export const LangContext = createContext();

export const LangProvider = ({ children }) => {
  const [lang, setLang] = useState("ar");
  const t = translations[lang];
  const toggle = () => setLang((l) => (l === "ar" ? "en" : "ar"));
  return (
    <LangContext.Provider value={{ lang, t, toggle }}>
      <div dir={t.dir} lang={t.lang}>
        {children}
      </div>
    </LangContext.Provider>
  );
};

export const useLang = () => useContext(LangContext);

export default translations;